- name: Deployment
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Print resource_index
    debug:
      msg: "hi"
  - name: Find out playbook's path
    shell: pwd
    register: playbook_path_output
  - debug: var=playbook_path_output.stdout