- name: Deployment
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Hello World
    debug:
      msg: "Hello World"
  - name: Find out playbook's path
    shell: pwd
    register: playbook_path_output
  - debug: var=playbook_path_output.stdout
