name: oidc

on:
  pull_request:
    branches:
      - main
      - feat/github-actions-aws-oidc
    paths:
      - iam/oidc/github/**
  push:
    branches:
      - main
      - feat/github-actions-aws-oidc
    paths:
      - iam/oidc/github/**
  workflow_dispatch:

jobs:
  build:
    name: oidc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::052275556902:role/github-actions
          role-session-name: aws

      - name: List Buckets
        run: |
          aws s3 ls
