name: oidc

on:
  pull_request:
    branches:
      - main
    paths:
      - aws/iam/oidc/github/**
  push:
    branches:
      - main
    paths:
      - aws/iam/oidc/github/**
  workflow_dispatch:

jobs:
  build:
    name: oidc
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/github-actions
          role-session-name: aws

      - name: List Buckets
        run: |
          aws s3 ls
